package com.chaplianski.bcard.domain.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty

@JsonIgnoreProperties(ignoreUnknown = true)
data class ContactCsv(
    @field:JsonProperty("Name") val name: String? = null,
    val givenName: String? = null,
    val additionalName: String? = null,
    val familyName: String? = null,
    val yomiName: String? = null,
    val givenNameYomi: String? = null,
    val additionalNameYomi: String? = null,
    val familyNameYomi: String? = null,
    val namePrefix: String? = null,
    val nameSuffix: String? = null,
    val initials: String? = null,
    val nickname: String? = null,
    val shortName: String? = null,
    val maidenName: String? = null,
    val birthday: String? = null,
    val gender: String? = null,
    val location: String? = null,
    val billingInformation: String? = null,
    val directoryServer: String? = null,
    val mileage: String? = null,
    val occupation: String? = null,
    val hobby: String? = null,
    val sensitivity: String? = null,
    val priority: String? = null,
    val subject: String? = null,
    val notes: String? = null,
    val language: String? = null,
    val photo: String? = null,
    val groupMembership: String? = null,
    val email1Type: String? = null,
    val email1Value: String? = null,
    val email2Type: String? = null,
    val email2Value: String? = null,
    val phone1Type: String? = null,
    val phone1Value: String? = null,
    val phone2Type: String? = null,
    val phone2Value: String? = null,
    val address1Type: String? = null,
    val address1Formatted: String? = null,
    val address1Street: String? = null,
    val address1City: String? = null,
    val address1POBox: String? = null,
    val address1Region: String? = null,
    val address1PostalCode: String? = null,
    val address1Country: String? = null,
    val address1ExtendedAddress: String? = null,
    val address2Type: String? = null,
    val address2Formatted: String? = null,
    val address2Street: String? = null,
    val address2City: String? = null,
    val address2POBox: String? = null,
    val address2Region: String? = null,
    val address2PostalCode: String? = null,
    val address2Country: String? = null,
    val address2ExtendedAddress: String? = null,
    val organization1Type: String? = null,
    val organization1Name: String? = null,
    val organization1YomiName: String? = null,
    val organization1Title: String? = null,
    val organization1Department: String? = null,
    val organization1Symbol: String? = null,
    val organization1Location: String? = null,
    val organization1JobDescription: String? = null,
    val website1Type: String? = null,
    val website1Value: String? = null,

    )
