package com.chaplianski.bcard.core.model

import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty

@JsonIgnoreProperties(ignoreUnknown = true)
data class ContactCsv(
    @field:JsonProperty("Name") var name: String? = null,
    @field:JsonProperty("Given Name") var givenName: String? = null,
    @field:JsonProperty("Additional Name") val additionalName: String? = null,
    @field:JsonProperty("Family Name") var familyName: String? = null,
    @field:JsonProperty("Yomi Name") val yomiName: String? = null,
    @field:JsonProperty("Given Name Yomi") val givenNameYomi: String? = null,
    @field:JsonProperty("Additional Name Yomi") val additionalNameYomi: String? = null,
    @field:JsonProperty("Family Name Yomi") val familyNameYomi: String? = null,
    @field:JsonProperty("Name Prefix") val namePrefix: String? = null,
    @field:JsonProperty("Name Suffix") val nameSuffix: String? = null,
    @field:JsonProperty("Initials") val initials: String? = null,
    @field:JsonProperty("Nickname") val nickname: String? = null,
    @field:JsonProperty("Short Name") val shortName: String? = null,
    @field:JsonProperty("Maiden Name") val maidenName: String? = null,
    @field:JsonProperty("Birthday") val birthday: String? = null,
    @field:JsonProperty("Gender") val gender: String? = null,
    @field:JsonProperty("Location") val location: String? = null,
    @field:JsonProperty("Billing Information") val billingInformation: String? = null,
    @field:JsonProperty("Directory Server") val directoryServer: String? = null,
    @field:JsonProperty("Mileage") val mileage: String? = null,
    @field:JsonProperty("Occupation") val occupation: String? = null,
    @field:JsonProperty("Hobby") val hobby: String? = null,
    @field:JsonProperty("Sensitivity") val sensitivity: String? = null,
    @field:JsonProperty("Priority") val priority: String? = null,
    @field:JsonProperty("Subject") val subject: String? = null,
    @field:JsonProperty("Notes") val notes: String? = null,
    @field:JsonProperty("Language") val language: String? = null,
    @field:JsonProperty("Photo") val photo: String? = null,
    @field:JsonProperty("Group Membership") val groupMembership: String? = null,
    @field:JsonProperty("E-mail 1 - Type") val email1Type: String? = null,
    @field:JsonProperty("E-mail 1 - Value") val email1Value: String? = null,
    @field:JsonProperty("E-mail 2 - Type") val email2Type: String? = null,
    @field:JsonProperty("E-mail 2 - Value") val email2Value: String? = null,
    @field:JsonProperty("Phone 1 - Type") val phone1Type: String? = null,
    @field:JsonProperty("Phone 1 - Value") val phone1Value: String? = null,
    @field:JsonProperty("Phone 2 - Type") val phone2Type: String? = null,
    @field:JsonProperty("Phone 2 - Value") val phone2Value: String? = null,
    @field:JsonProperty("Address 1 - Type") val address1Type: String? = null,
    @field:JsonProperty("Address 1 - Formatted") val address1Formatted: String? = null,
    @field:JsonProperty("Address 1 - Street") val address1Street: String? = null,
    @field:JsonProperty("Address 1 - City") val address1City: String? = null,
    @field:JsonProperty("Address 1 - PO Box") val address1POBox: String? = null,
    @field:JsonProperty("Address 1 - Region") val address1Region: String? = null,
    @field:JsonProperty("Address 1 - Postal Code") val address1PostalCode: String? = null,
    @field:JsonProperty("Address 1 - Country") val address1Country: String? = null,
    @field:JsonProperty("Address 1 - Extended Address") val address1ExtendedAddress: String? = null,
    @field:JsonProperty("Address 2 - Type") val address2Type: String? = null,
    @field:JsonProperty("Address 2 - Formatted") val address2Formatted: String? = null,
    @field:JsonProperty("Address 2 - Street") val address2Street: String? = null,
    @field:JsonProperty("Address 2 - City") val address2City: String? = null,
    @field:JsonProperty("Address 2 - PO Box") val address2POBox: String? = null,
    @field:JsonProperty("Address 2 - Region") val address2Region: String? = null,
    @field:JsonProperty("Address 2 - Postal Code") val address2PostalCode: String? = null,
    @field:JsonProperty("Address 2 - Country") val address2Country: String? = null,
    @field:JsonProperty("Address 2 - Extended Address") val address2ExtendedAddress: String? = null,
    @field:JsonProperty("Organization 1 - Type") val organization1Type: String? = null,
    @field:JsonProperty("Organization 1 - Name") val organization1Name: String? = null,
    @field:JsonProperty("Organization 1 - Yomi Name") val organization1YomiName: String? = null,
    @field:JsonProperty("Organization 1 - Title") val organization1Title: String? = null,
    @field:JsonProperty("Organization 1 - Department") val organization1Department: String? = null,
    @field:JsonProperty("Organization 1 - Symbol") val organization1Symbol: String? = null,
    @field:JsonProperty("Organization 1 - Location") val organization1Location: String? = null,
    @field:JsonProperty("Organization 1 - Job Description") val organization1JobDescription: String? = null,
    @field:JsonProperty("Website 1 - Type") val website1Type: String? = null,
    @field:JsonProperty("Website 1 - Value") val website1Value: String? = null
)
